# Generated by Django 2.2.7 on 2019-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('rate_movie', 'Can rate the movie'), ('close_movie', 'Can remove a movie by setting its status as closed')]},
        ),
    ]
